FROM coin-base
WORKDIR /app/apps/api-server
EXPOSE 3000
CMD ["sh", "-c", "pnpm --filter @coin/database db:generate && pnpm --filter @coin/database build && pnpm --filter @coin/kafka-contracts build && pnpm --filter @coin/database exec prisma migrate deploy && pnpm dev"]
