import {
  Controller,
  Get,
  Post,
  Patch,
  Delete,
  Body,
  Param,
  Query,
  HttpCode,
  HttpStatus,
} from '@nestjs/common';
import {
  ApiTags,
  ApiBearerAuth,
  ApiOperation,
  ApiResponse,
  ApiParam,
  ApiQuery,
} from '@nestjs/swagger';
import { CommandBus, QueryBus } from '@nestjs/cqrs';
import { CurrentUser } from '../auth/decorators/current-user.decorator';
import {
  CreateStrategyCommand,
  UpdateStrategyCommand,
  ToggleStrategyCommand,
  DeleteStrategyCommand,
} from './commands';
import {
  GetStrategiesQuery,
  GetStrategyQuery,
  GetStrategyLogsQuery,
  GetStrategyPerformanceQuery,
  GetStrategySignalsQuery,
} from './queries';
import { CreateStrategyDto } from './dto/create-strategy.dto';
import { UpdateStrategyDto } from './dto/update-strategy.dto';
import type { User } from '@coin/database';

@ApiTags('Strategies')
@ApiBearerAuth('access-token')
@Controller('strategies')
export class StrategiesController {
  constructor(
    private readonly commandBus: CommandBus,
    private readonly queryBus: QueryBus,
  ) {}

  @Post()
  @ApiOperation({ summary: 'Create a new trading strategy' })
  @ApiResponse({ status: 201, description: 'Strategy created successfully' })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  async create(@CurrentUser() user: User, @Body() dto: CreateStrategyDto) {
    return this.commandBus.execute(new CreateStrategyCommand(user.id, dto));
  }

  @Get()
  @ApiOperation({ summary: 'List all strategies for the current user' })
  @ApiResponse({ status: 200, description: 'List of strategies returned' })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  async findAll(@CurrentUser() user: User) {
    return this.queryBus.execute(new GetStrategiesQuery(user.id));
  }

  @Get(':id')
  @ApiOperation({ summary: 'Retrieve a specific strategy by its ID' })
  @ApiResponse({ status: 200, description: 'Strategy details returned' })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  @ApiParam({ name: 'id', description: 'Strategy ID' })
  async findOne(@CurrentUser() user: User, @Param('id') id: string) {
    return this.queryBus.execute(new GetStrategyQuery(user.id, id));
  }

  @Patch(':id')
  @ApiOperation({ summary: 'Update an existing strategy configuration' })
  @ApiResponse({ status: 200, description: 'Strategy updated successfully' })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  @ApiParam({ name: 'id', description: 'Strategy ID' })
  async update(@CurrentUser() user: User, @Param('id') id: string, @Body() dto: UpdateStrategyDto) {
    return this.commandBus.execute(new UpdateStrategyCommand(user.id, id, dto));
  }

  @Patch(':id/toggle')
  @ApiOperation({ summary: 'Toggle a strategy between active and paused states' })
  @ApiResponse({ status: 200, description: 'Strategy toggled successfully' })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  @ApiParam({ name: 'id', description: 'Strategy ID' })
  async toggle(@CurrentUser() user: User, @Param('id') id: string) {
    return this.commandBus.execute(new ToggleStrategyCommand(user.id, id));
  }

  @Delete(':id')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Delete a strategy permanently' })
  @ApiResponse({ status: 200, description: 'Strategy deleted successfully' })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  @ApiParam({ name: 'id', description: 'Strategy ID' })
  async remove(@CurrentUser() user: User, @Param('id') id: string) {
    return this.commandBus.execute(new DeleteStrategyCommand(user.id, id));
  }

  @Get(':id/performance')
  @ApiOperation({ summary: 'Retrieve performance metrics for a strategy' })
  @ApiResponse({ status: 200, description: 'Strategy performance data returned' })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  @ApiParam({ name: 'id', description: 'Strategy ID' })
  async getPerformance(@CurrentUser() user: User, @Param('id') id: string) {
    return this.queryBus.execute(new GetStrategyPerformanceQuery(user.id, id));
  }

  @Get(':id/signals')
  @ApiOperation({ summary: 'List trading signals generated by a strategy' })
  @ApiResponse({ status: 200, description: 'Strategy signals returned' })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  @ApiParam({ name: 'id', description: 'Strategy ID' })
  async getSignals(@CurrentUser() user: User, @Param('id') id: string) {
    return this.queryBus.execute(new GetStrategySignalsQuery(user.id, id));
  }

  @Get(':id/logs')
  @ApiOperation({ summary: 'List execution logs for a strategy with optional filters' })
  @ApiResponse({ status: 200, description: 'Paginated strategy logs returned' })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  @ApiParam({ name: 'id', description: 'Strategy ID' })
  @ApiQuery({ name: 'cursor', required: false, description: 'Cursor for pagination' })
  @ApiQuery({ name: 'limit', required: false, description: 'Number of items per page' })
  @ApiQuery({ name: 'action', required: false, description: 'Filter by log action type' })
  @ApiQuery({ name: 'signal', required: false, description: 'Filter by signal type' })
  async getLogs(
    @CurrentUser() user: User,
    @Param('id') id: string,
    @Query('cursor') cursor?: string,
    @Query('limit') limit?: string,
    @Query('action') action?: string,
    @Query('signal') signal?: string,
  ) {
    return this.queryBus.execute(
      new GetStrategyLogsQuery(
        user.id,
        id,
        cursor,
        limit ? parseInt(limit, 10) : undefined,
        action,
        signal,
      ),
    );
  }
}
