services:
  web:
    build:
      target: development
    volumes:
      - ../apps/web:/app/apps/web
      - ../packages:/app/packages
      - /app/apps/web/node_modules
      - /app/apps/web/.next
    command: pnpm --filter web dev

  api-server:
    build:
      target: development
    volumes:
      - ../apps/api-server:/app/apps/api-server
      - ../packages:/app/packages
      - /app/apps/api-server/node_modules
    command: pnpm --filter api-server dev

  worker-service:
    build:
      target: development
    volumes:
      - ../apps/worker-service:/app/apps/worker-service
      - ../packages:/app/packages
      - /app/apps/worker-service/node_modules
    command: pnpm --filter worker-service dev
